###########################################
###########################################
## Dockerfile to run GitHub Super-Linter ##
###########################################
###########################################
##################
# Get base image #
##################
FROM github/super-linter:v3.6.0
RUN npm -g --no-cache install \
    tap-xunit@2.4.1 && \
    pip install --no-cache-dir \
    requests \
    click

###########################################
# Load GitHub Env Vars for GitHub Actions #
###########################################
ENV ACTIONS_RUNNER_DEBUG=${ACTIONS_RUNNER_DEBUG} \
    ANSIBLE_DIRECTORY=${ANSIBLE_DIRECTORY} \
    DEFAULT_BRANCH=${DEFAULT_BRANCH} \
    DISABLE_ERRORS=${DISABLE_ERRORS} \
    GITHUB_EVENT_PATH=${GITHUB_EVENT_PATH} \
    GITHUB_SHA=${GITHUB_SHA} \
    GITHUB_TOKEN=${GITHUB_TOKEN} \
    GITHUB_WORKSPACE=${GITHUB_WORKSPACE} \
    LINTER_RULES_PATH=${LINTER_RULES_PATH} \
    LOG_FILE=${LOG_FILE} \
    LOG_LEVEL=${LOG_LEVEL} \
    OUTPUT_DETAILS=${OUTPUT_DETAILS} \
    OUTPUT_FOLDER=${OUTPUT_FOLDER} \
    OUTPUT_FORMAT=${OUTPUT_FORMAT} \
    RUN_LOCAL=${RUN_LOCAL} \
    TEST_CASE_RUN=${TEST_CASE_RUN} \
    VALIDATE_ALL_CODEBASE=${VALIDATE_ALL_CODEBASE} \
    VALIDATE_ANSIBLE=${VALIDATE_ANSIBLE} \
    VALIDATE_ARM=${VALIDATE_ARM} \
    VALIDATE_BASH=${VALIDATE_BASH} \
    VALIDATE_CLOJURE=${VALIDATE_CLOJURE} \
    VALIDATE_CLOUDFORMATION=${VALIDATE_CLOUDFORMATION} \
    VALIDATE_COFFEE=${VALIDATE_COFFEE} \
    VALIDATE_CSS=${VALIDATE_CSS} \
    VALIDATE_DART=${VALIDATE_DART} \
    VALIDATE_DOCKER=${VALIDATE_DOCKER} \
    VALIDATE_DOCKER_HADOLINT=${VALIDATE_DOCKER_HADOLINT} \
    VALIDATE_EDITORCONFIG=${VALIDATE_EDITORCONFIG} \
    VALIDATE_ENV=${VALIDATE_ENV} \
    VALIDATE_GO=${VALIDATE_GO} \
    VALIDATE_HTML=${VALIDATE_HTML} \
    VALIDATE_JAVA=${VALIDATE_JAVA} \
    VALIDATE_JAVASCRIPT_ES=${VALIDATE_JAVASCRIPT_ES} \
    VALIDATE_JAVASCRIPT_STANDARD=${VALIDATE_JAVASCRIPT_STANDARD} \
    VALIDATE_JSON=${VALIDATE_JSON} \
    VALIDATE_KOTLIN=${VALIDATE_KOTLIN} \
    VALIDATE_LUA=${VALIDATE_LUA} \
    VALIDATE_MD=${VALIDATE_MD} \
    VALIDATE_OPENAPI=${VALIDATE_OPENAPI} \
    VALIDATE_PERL=${VALIDATE_PERL} \
    VALIDATE_PHP=${VALIDATE_PHP} \
    VALIDATE_PHP_BUILTIN=${VALIDATE_PHP_BUILTIN} \
    VALIDATE_PHP_PHPCS=${VALIDATE_PHP_PHPCS} \
    VALIDATE_PHP_PHPSTAN=${VALIDATE_PHP_PHPSTAN} \
    VALIDATE_PHP_PSALM=${VALIDATE_PHP_PSALM} \
    VALIDATE_POWERSHELL=${VALIDATE_POWERSHELL} \
    VALIDATE_PROTOBUF=${VALIDATE_PROTOBUF} \
    VALIDATE_PYTHON=${VALIDATE_PYTHON} \
    VALIDATE_PYTHON_PYLINT=${VALIDATE_PYTHON_PYLINT} \
    VALIDATE_PYTHON_FLAKE8=${VALIDATE_PYTHON_FLAKE8} \
    VALIDATE_RAKU=${VALIDATE_RAKU} \
    VALIDATE_RUBY=${VALIDATE_RUBY} \
    VALIDATE_STATES=${VALIDATE_STATES} \
    VALIDATE_SQL=${VALIDATE_SQL} \
    VALIDATE_TERRAFORM=${VALIDATE_TERRAFORM} \
    VALIDATE_TERRAFORM_TERRASCAN=${VALIDATE_TERRAFORM_TERRASCAN} \
    VALIDATE_TYPESCRIPT_ES=${VALIDATE_TYPESCRIPT_ES} \
    VALIDATE_TYPESCRIPT_STANDARD=${VALIDATE_TYPESCRIPT_STANDARD} \
    VALIDATE_XML=${VALIDATE_XML} \
    VALIDATE_YAML=${VALIDATE_YAML} \
    BITBUCKET_CODENOTIFY=${BITBUCKET_CODENOTIFY}


#############################
# Copy scripts to container #
#############################
COPY lib /action/lib

##################################
# Copy linter rules to container #
##################################
COPY TEMPLATES /action/lib/.automation

######################
# Set the entrypoint #
######################
ENTRYPOINT ["/action/lib/linter.sh"]
